import { BillingSnapshot } from "./types";

const day = (month: string, date: number) => `2026-${month}-${String(date).padStart(2, "0")}`;

export const mockSnapshot: BillingSnapshot = {
  users: [
    { id: "user-hiroki", name: "Hiroki", role: "Hiroki", active: true },
    { id: "user-billing", name: "Billing Staff", role: "Billing Staff", active: true },
    { id: "user-accounting", name: "Accounting", role: "Accounting", active: true },
  ],
  clients: [
    { id: "client-ringer", name: "Ringer Hut", active: true, createdAt: day("01", 5) },
    { id: "client-machida", name: "Machida Shoten", active: true, createdAt: day("01", 12) },
    { id: "client-matcha", name: "Matcha Times", active: true, createdAt: day("02", 3) },
    { id: "client-north", name: "North Studio", active: true, createdAt: day("02", 20) },
  ],
  projects: [
    {
      id: "project-home-fair",
      clientId: "client-ringer",
      name: "Home Fair Special Set",
      date: day("08", 28),
      createdAt: day("08", 28),
      createdBy: "Hiroki",
      updatedAt: day("08", 28),
      updatedBy: "Hiroki",
    },
    {
      id: "project-lunch-menu",
      clientId: "client-ringer",
      name: "Lunch Menu",
      date: day("08", 26),
      createdAt: day("08", 26),
      createdBy: "Hiroki",
      updatedAt: day("08", 29),
      updatedBy: "Hiroki",
    },
    {
      id: "project-tonkatsu",
      clientId: "client-ringer",
      name: "Tonkatsu Promo",
      date: day("08", 24),
      createdAt: day("08", 24),
      createdBy: "Hiroki",
      updatedAt: day("08", 24),
      updatedBy: "Hiroki",
    },
    {
      id: "project-payday",
      clientId: "client-ringer",
      name: "Pay Day Campaign",
      date: day("08", 21),
      createdAt: day("08", 21),
      createdBy: "Hiroki",
      updatedAt: day("08", 27),
      updatedBy: "Accounting",
    },
    {
      id: "project-deliver",
      clientId: "client-ringer",
      name: "Deliver Banner",
      date: day("08", 19),
      createdAt: day("08", 19),
      createdBy: "Hiroki",
      updatedAt: day("08", 20),
      updatedBy: "Billing Staff",
    },
    {
      id: "project-machida-autumn",
      clientId: "client-machida",
      name: "Autumn Menu Refresh",
      date: day("08", 17),
      createdAt: day("08", 17),
      createdBy: "Hiroki",
      updatedAt: day("08", 22),
      updatedBy: "Hiroki",
    },
    {
      id: "project-matcha-site",
      clientId: "client-matcha",
      name: "Editorial Site Update",
      date: day("07", 31),
      createdAt: day("07", 31),
      createdBy: "Hiroki",
      updatedAt: day("08", 14),
      updatedBy: "Accounting",
    },
    {
      id: "project-north-brand",
      clientId: "client-north",
      name: "Brand Guidelines",
      date: day("06", 18),
      createdAt: day("06", 18),
      createdBy: "Hiroki",
      updatedAt: day("07", 2),
      updatedBy: "Accounting",
    },
  ],
  billingItems: [
    { id: "item-home-banner", projectId: "project-home-fair", description: "Home Fair Banner", type: "Design", quantity: 1, unitPrice: 60, amount: 60, status: "IN_PROGRESS", createdAt: day("08", 28), createdBy: "Hiroki", updatedAt: day("08", 28), updatedBy: "Hiroki" },
    { id: "item-home-set", projectId: "project-home-fair", description: "Special Set Layout", type: "Design", quantity: 1, unitPrice: 100, amount: 100, status: "IN_PROGRESS", createdAt: day("08", 28), createdBy: "Hiroki", updatedAt: day("08", 28), updatedBy: "Hiroki" },
    { id: "item-lunch-a3", projectId: "project-lunch-menu", description: "A3 Design", type: "Design", quantity: 1, unitPrice: 125, amount: 125, status: "READY_TO_INVOICE", createdAt: day("08", 26), createdBy: "Hiroki", updatedAt: day("08", 29), updatedBy: "Hiroki" },
    { id: "item-lunch-istand", projectId: "project-lunch-menu", description: "iStand Resize", type: "Resize", quantity: 1, unitPrice: 25, amount: 25, status: "READY_TO_INVOICE", createdAt: day("08", 26), createdBy: "Hiroki", updatedAt: day("08", 29), updatedBy: "Hiroki" },
    { id: "item-lunch-sns", projectId: "project-lunch-menu", description: "SNS Resize", type: "Resize", quantity: 1, unitPrice: 25, amount: 25, status: "READY_TO_INVOICE", createdAt: day("08", 26), createdBy: "Hiroki", updatedAt: day("08", 29), updatedBy: "Hiroki" },
    { id: "item-lunch-print", projectId: "project-lunch-menu", description: "Print ×40", type: "Print", quantity: 40, unitPrice: 1.25, amount: 50, status: "READY_TO_INVOICE", createdAt: day("08", 26), createdBy: "Hiroki", updatedAt: day("08", 29), updatedBy: "Hiroki" },
    { id: "item-tonkatsu-design", projectId: "project-tonkatsu", description: "Tonkatsu Promo Design", type: "Design", quantity: 1, unitPrice: 100, amount: 100, status: "READY_TO_INVOICE", createdAt: day("08", 24), createdBy: "Hiroki", updatedAt: day("08", 24), updatedBy: "Hiroki" },
    { id: "item-tonkatsu-social", projectId: "project-tonkatsu", description: "Social Resize", type: "Resize", quantity: 1, unitPrice: 25, amount: 25, status: "READY_TO_INVOICE", createdAt: day("08", 24), createdBy: "Hiroki", updatedAt: day("08", 24), updatedBy: "Hiroki" },
    { id: "item-payday-keyvisual", projectId: "project-payday", description: "Key Visual", type: "Design", quantity: 1, unitPrice: 100, amount: 100, status: "INVOICED", createdAt: day("08", 21), createdBy: "Hiroki", updatedAt: day("08", 27), updatedBy: "Accounting" },
    { id: "item-payday-resize", projectId: "project-payday", description: "SNS Resize Set", type: "Resize", quantity: 1, unitPrice: 50, amount: 50, status: "INVOICED", createdAt: day("08", 21), createdBy: "Hiroki", updatedAt: day("08", 27), updatedBy: "Accounting" },
    { id: "item-deliver-banner", projectId: "project-deliver", description: "Deliver Banner", type: "Design", quantity: 1, unitPrice: 60, amount: 60, status: "NEEDS_REVIEW", createdAt: day("08", 19), createdBy: "Hiroki", updatedAt: day("08", 20), updatedBy: "Billing Staff" },
    { id: "item-deliver-home", projectId: "project-deliver", description: "Home Fair Adaptation", type: "Resize", quantity: 1, unitPrice: 100, amount: 100, status: "NEEDS_REVIEW", createdAt: day("08", 19), createdBy: "Hiroki", updatedAt: day("08", 20), updatedBy: "Billing Staff" },
    { id: "item-machida-menu", projectId: "project-machida-autumn", description: "Menu Layout", type: "Design", quantity: 1, unitPrice: 180, amount: 180, status: "READY_TO_INVOICE", createdAt: day("08", 17), createdBy: "Hiroki", updatedAt: day("08", 22), updatedBy: "Hiroki" },
    { id: "item-machida-print", projectId: "project-machida-autumn", description: "Print ×100", type: "Print", quantity: 100, unitPrice: 1.2, amount: 120, status: "READY_TO_INVOICE", createdAt: day("08", 17), createdBy: "Hiroki", updatedAt: day("08", 22), updatedBy: "Hiroki" },
    { id: "item-matcha-hero", projectId: "project-matcha-site", description: "Homepage Direction", type: "Design", quantity: 1, unitPrice: 240, amount: 240, status: "PAID", createdAt: day("07", 31), createdBy: "Hiroki", updatedAt: day("08", 14), updatedBy: "Accounting" },
    { id: "item-matcha-mobile", projectId: "project-matcha-site", description: "Mobile Adaptation", type: "Resize", quantity: 1, unitPrice: 80, amount: 80, status: "PAID", createdAt: day("07", 31), createdBy: "Hiroki", updatedAt: day("08", 14), updatedBy: "Accounting" },
    { id: "item-north-system", projectId: "project-north-brand", description: "Identity System", type: "Design", quantity: 1, unitPrice: 420, amount: 420, status: "PAID", createdAt: day("06", 18), createdBy: "Hiroki", updatedAt: day("07", 2), updatedBy: "Accounting" },
  ],
  invoices: [
    { id: "invoice-aug-001", clientId: "client-ringer", invoiceNumber: "CIJD-2026-08-001", invoiceDate: day("08", 27), amount: 150, status: "OPEN", createdAt: day("08", 27), paymentSlip: "payment-slip-aug-001.pdf", receiptStatus: "PENDING" },
    { id: "invoice-jul-014", clientId: "client-matcha", invoiceNumber: "CIJD-2026-07-014", invoiceDate: day("08", 5), amount: 320, status: "PAID", createdAt: day("08", 5), paymentDate: day("08", 14), paymentSlip: "payment-slip-jul-014.pdf", receiptStatus: "RECEIVED" },
    { id: "invoice-jun-009", clientId: "client-north", invoiceNumber: "CIJD-2026-06-009", invoiceDate: day("06", 24), amount: 420, status: "PAID", createdAt: day("06", 24), paymentDate: day("07", 2), paymentSlip: "payment-slip-jun-009.pdf", receiptStatus: "PENDING" },
  ],
  invoiceItems: [
    { invoiceId: "invoice-aug-001", billingItemId: "item-payday-keyvisual" },
    { invoiceId: "invoice-aug-001", billingItemId: "item-payday-resize" },
    { invoiceId: "invoice-jul-014", billingItemId: "item-matcha-hero" },
    { invoiceId: "invoice-jul-014", billingItemId: "item-matcha-mobile" },
    { invoiceId: "invoice-jun-009", billingItemId: "item-north-system" },
  ],
  payments: [
    { id: "payment-jul-014", invoiceId: "invoice-jul-014", paymentDate: day("08", 14), createdAt: day("08", 14), createdBy: "Accounting" },
    { id: "payment-jun-009", invoiceId: "invoice-jun-009", paymentDate: day("07", 2), createdAt: day("07", 2), createdBy: "Accounting" },
  ],
  auditLogs: [],
};
