import type { SupabaseClient } from "@supabase/supabase-js";
import { assertIssueable, calculateTaxInvoice, type TaxInvoiceLineDraft } from "@/lib/tax-invoice-v4";
import type { V4Customer, V4Invoice } from "./types";

type CustomerInput = { name: string; khmerName?: string | null; address?: string | null; phone?: string | null; vatin?: string | null };
type DraftInput = { customerId?: string | null; customer?: CustomerInput; invoiceDate: string; exchangeRate?: string | number | null; exchangeRateSource?: string | null; exchangeRateDate?: string | null; exchangeRateManualOverride?: boolean; lines: TaxInvoiceLineDraft[] };

const customer = (row: any): V4Customer => ({ id: row.id, name: row.name, khmerName: row.khmer_name ?? null, address: row.address ?? null, phone: row.phone ?? null, vatin: row.vatin ?? null });
const line = (row: any): TaxInvoiceLineDraft => ({ id: row.id, sourceType: row.source_type, billingItemId: row.billing_item_id, description: row.description, quantity: String(row.quantity), unitPrice: String(row.unit_price), sortOrder: row.sort_order });
function invoice(row: any, lines: any[]): V4Invoice { return { id: row.id, invoiceNumber: row.invoice_number, status: row.status, invoiceDate: row.invoice_date, customerId: row.customer_id, customerName: row.customer_name, customerKhmerName: row.customer_khmer_name, customerAddress: row.customer_address, customerPhone: row.customer_phone, customerVatin: row.customer_vatin, lines: lines.map(line), subtotal: String(row.subtotal), vatRate: String(row.vat_rate), vatAmount: String(row.vat_amount), usdTotal: String(row.usd_total), exchangeRate: row.exchange_rate == null ? null : String(row.exchange_rate), exchangeRateSource: row.exchange_rate_source, exchangeRateDate: row.exchange_rate_date, exchangeRateManualOverride: !!row.exchange_rate_manual_override, khrTotal: row.khr_total == null ? null : String(row.khr_total), issuedAt: row.issued_at, cancelledAt: row.cancelled_at, createdAt: row.created_at, updatedAt: row.updated_at }; }

export class V4TaxInvoiceRepository {
  constructor(private readonly db: SupabaseClient) {}

  async listCustomers(search = ""): Promise<V4Customer[]> {
    let query = this.db.from("v4_customers").select("*").order("name");
    if (search.trim()) query = query.ilike("name", `%${search.trim()}%`);
    const result = await query; if (result.error) throw result.error; return (result.data ?? []).map(customer);
  }
  async createCustomer(input: CustomerInput): Promise<V4Customer> { const result = await this.db.from("v4_customers").insert({ name: input.name.trim(), khmer_name: input.khmerName ?? null, address: input.address ?? null, phone: input.phone ?? null, vatin: input.vatin ?? null }).select().single(); if (result.error) throw result.error; return customer(result.data); }
  async updateCustomer(id: string, input: Partial<CustomerInput>): Promise<V4Customer> { const patch: Record<string, unknown> = {}; if (input.name !== undefined) patch.name = input.name.trim(); if (input.khmerName !== undefined) patch.khmer_name = input.khmerName; if (input.address !== undefined) patch.address = input.address; if (input.phone !== undefined) patch.phone = input.phone; if (input.vatin !== undefined) patch.vatin = input.vatin; const result = await this.db.from("v4_customers").update(patch).eq("id", id).select().single(); if (result.error) throw result.error; return customer(result.data); }

  private async withLines(rows: any[]): Promise<V4Invoice[]> { if (!rows.length) return []; const ids = rows.map((row) => row.id); const result = await this.db.from("v4_tax_invoice_lines").select("*").in("invoice_id", ids).order("sort_order"); if (result.error) throw result.error; return rows.map((row) => invoice(row, (result.data ?? []).filter((lineRow) => lineRow.invoice_id === row.id))); }
  async listInvoices(search = ""): Promise<V4Invoice[]> { let query = this.db.from("v4_tax_invoices").select("*").order("created_at", { ascending: false }); if (search.trim()) query = query.or(`invoice_number.ilike.%${search.trim()}%,customer_name.ilike.%${search.trim()}%`); const result = await query; if (result.error) throw result.error; return this.withLines(result.data ?? []); }
  async getInvoice(id: string): Promise<V4Invoice> { const result = await this.db.from("v4_tax_invoices").select("*").eq("id", id).single(); if (result.error) throw result.error; return (await this.withLines([result.data]))[0]; }

  private async customerSnapshot(input: DraftInput): Promise<{ id: string | null; name: string; khmer_name: string | null; address: string | null; phone: string | null; vatin: string | null }> {
    if (!input.customerId) { if (!input.customer?.name) throw new Error("Customer is required"); return { id: null, name: input.customer.name, khmer_name: input.customer.khmerName ?? null, address: input.customer.address ?? null, phone: input.customer.phone ?? null, vatin: input.customer.vatin ?? null }; }
    const result = await this.db.from("v4_customers").select("*").eq("id", input.customerId).single(); if (result.error) throw result.error; const c = customer(result.data); return { id: c.id, name: c.name, khmer_name: c.khmerName, address: c.address, phone: c.phone, vatin: c.vatin };
  }
  async createDraft(input: DraftInput): Promise<V4Invoice> { const c = await this.customerSnapshot(input); const totals = calculateTaxInvoice(input.lines, input.exchangeRate); const head = await this.db.from("v4_tax_invoices").insert({ status: "DRAFT", invoice_date: input.invoiceDate, customer_id: c.id, customer_name: c.name, customer_khmer_name: c.khmer_name, customer_address: c.address, customer_phone: c.phone, customer_vatin: c.vatin, subtotal: totals.subtotal, vat_rate: 0.1, vat_amount: totals.vatAmount, usd_total: totals.usdTotal, exchange_rate: input.exchangeRate ?? null, exchange_rate_source: input.exchangeRateSource ?? null, exchange_rate_date: input.exchangeRateDate ?? null, exchange_rate_manual_override: input.exchangeRateManualOverride ?? false, khr_total: totals.khrTotal }).select().single(); if (head.error) throw head.error; await this.replaceLines(head.data.id, input.lines); return this.getInvoice(head.data.id); }
  async replaceLines(id: string, lines: TaxInvoiceLineDraft[]): Promise<void> { const current = await this.db.from("v4_tax_invoices").select("status").eq("id", id).single(); if (current.error) throw current.error; if (current.data.status !== "DRAFT") throw new Error("Only Draft invoices can be edited"); const removed = await this.db.from("v4_tax_invoice_lines").delete().eq("invoice_id", id); if (removed.error) throw removed.error; if (lines.length) { const result = await this.db.from("v4_tax_invoice_lines").insert(lines.map((item, index) => ({ invoice_id: id, source_type: item.sourceType, billing_item_id: item.billingItemId ?? null, description: item.description, quantity: item.quantity, unit_price: item.unitPrice, amount: calculateTaxInvoice([item]).subtotal, sort_order: index }))); if (result.error) throw result.error; } }
  async updateDraft(id: string, input: DraftInput): Promise<V4Invoice> { const c = await this.customerSnapshot(input); const totals = calculateTaxInvoice(input.lines, input.exchangeRate); const result = await this.db.from("v4_tax_invoices").update({ invoice_date: input.invoiceDate, customer_id: c.id, customer_name: c.name, customer_khmer_name: c.khmer_name, customer_address: c.address, customer_phone: c.phone, customer_vatin: c.vatin, subtotal: totals.subtotal, vat_amount: totals.vatAmount, usd_total: totals.usdTotal, exchange_rate: input.exchangeRate ?? null, exchange_rate_source: input.exchangeRateSource ?? null, exchange_rate_date: input.exchangeRateDate ?? null, exchange_rate_manual_override: input.exchangeRateManualOverride ?? false, khr_total: totals.khrTotal, updated_at: new Date().toISOString() }).eq("id", id).eq("status", "DRAFT").select().single(); if (result.error) throw result.error; await this.replaceLines(id, input.lines); return this.getInvoice(id); }
  async issue(id: string): Promise<V4Invoice> { const draft = await this.getInvoice(id); assertIssueable({ customerName: draft.customerName, invoiceDate: draft.invoiceDate, lines: draft.lines, exchangeRate: draft.exchangeRate }); const result = await this.db.rpc("v4_issue_tax_invoice", { p_invoice_id: id }); if (result.error) throw result.error; return this.getInvoice(id); }
  async cancel(id: string): Promise<V4Invoice> { const result = await this.db.from("v4_tax_invoices").update({ status: "CANCELLED", cancelled_at: new Date().toISOString(), updated_at: new Date().toISOString() }).eq("id", id).eq("status", "ISSUED").select().single(); if (result.error) throw result.error; return this.getInvoice(result.data.id); }
  async duplicate(id: string): Promise<V4Invoice> { const source = await this.getInvoice(id); return this.createDraft({ customerId: source.customerId, invoiceDate: new Date().toISOString().slice(0, 10), exchangeRate: source.exchangeRate, exchangeRateSource: source.exchangeRateSource, exchangeRateDate: source.exchangeRateDate, lines: source.lines.map((item) => ({ ...item, id: crypto.randomUUID(), billingItemId: item.sourceType === "BILLING_ITEM" ? item.billingItemId : null })) }); }
}
