import { spawnSync } from "node:child_process";
import { writeFile } from "node:fs/promises";

const commit =
  process.env.CIJD_BUILD_COMMIT?.trim() ||
  process.env.WORKERS_CI_COMMIT_SHA?.trim() ||
  "unknown";
const branch =
  process.env.CIJD_BUILD_BRANCH?.trim() ||
  process.env.WORKERS_CI_BRANCH?.trim() ||
  "unknown";
const builtAt = process.env.CIJD_BUILT_AT?.trim() || new Date().toISOString();
const environment =
  process.env.CIJD_BUILD_ENVIRONMENT?.trim() ||
  (process.env.WORKERS_CI === "1" ? "review" : "unknown");

const source = `// Generated by scripts/build-vinext.mjs. Do not hand-edit.\nexport const GENERATED_BUILD_INFO = ${JSON.stringify(
  { commit, branch, builtAt, environment },
  null,
  2,
)} as const;\n`;

await writeFile("src/lib/build-info.generated.ts", source, "utf8");

console.log(`[CIJD] build identity ${commit.slice(0, 8)} ${branch} ${environment}`);
const result = spawnSync("npx", ["vinext", "build"], {
  stdio: "inherit",
  env: {
    ...process.env,
    CIJD_BUILD_COMMIT: commit,
    CIJD_BUILD_BRANCH: branch,
    CIJD_BUILT_AT: builtAt,
    CIJD_BUILD_ENVIRONMENT: environment,
  },
});
if (result.status !== 0) process.exit(result.status ?? 1);
